final products = [
  {
    'id': '0',
    'title': 'Puma Shoes',
    'price': 82.66,
    'imageUrl': 'assets/images/puma_2.png',
    'company': 'Puma',
    'tag': 'product',
    'sizes': [8, 9, 10, 11],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '1',
    'title': 'Addidas Shoes',
    'price': 94.67,
    'imageUrl': 'assets/images/adidas_2.png',
    'company': 'Addidas',
    'tag': 'product',
    'sizes': [9, 10, 11, 12],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '2',
    'title': 'Bata Shoes',
    'price': 82.66,
    'imageUrl': 'assets/images/bata_1.png',
    'company': 'Bata',
    'tag': 'product',
    'sizes': [8, 9],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '3',
    'title': 'Bata Men\'s Shoes',
    'price': 123.67,
    'imageUrl': 'assets/images/bata_2.png',
    'company': 'Bata',
    'tag': 'product',
    'sizes': [8, 9, 10],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '4',
    'title': 'Converse Shoes',
    'price': 94.67,
    'imageUrl': 'assets/images/converse_1.png',
    'company': 'Converse',
    'tag': 'product',
    'sizes': [9, 10, 11, 12],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '5',
    'title': 'Nike Shoes',
    'price': 82.66,
    'imageUrl': 'assets/images/nike_1.png',
    'company': 'Nike',
    'tag': 'product',
    'sizes': [8, 9, 10, 11],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '6',
    'title': 'Nike Shoes',
    'price': 82.66,
    'imageUrl': 'assets/images/nike_2.png',
    'company': 'Nike',
    'tag': 'product',
    'sizes': [8, 9, 10, 11],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '7',
    'title': 'Nike Shoes',
    'price': 82.66,
    'imageUrl': 'assets/images/nike_3.png',
    'company': 'Nike',
    'tag': 'product',
    'sizes': [8, 9, 10, 11],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '8',
    'title': 'Puma Shoes',
    'price': 82.66,
    'imageUrl': 'assets/images/puma_1.png',
    'company': 'Puma',
    'tag': 'product',
    'sizes': [8, 9, 10, 11],
    'bgcolor': 'Colors.white',
  },
  {
    'id': '9',
    'title': 'Adidas Ultrafly',
    'price': 41.55,
    'imageUrl': 'assets/images/adidas_1.png',
    'company': 'Adidas',
    'tag': 'product',
    'sizes': [10, 11, 12],
    'bgcolor': 'Colors.white',
  },
];
